[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PhIAT"
authors = [{name = "TITAN Collaboration", email = "aczihaly@triumf.ca"}]
dynamic = ["version", "description"]
